### ISSUE TITLE
Mod seems to break melee attack animations

### ISSUE THREAD

**Issue by SubtleWinter** [TaleSpire-Modding/RadialUIPlugin#12]
this mod seems to break attack animations, i decided to do some testing and eventually found disabling this mod fixed the issue. creating a new profile and downloading just this mod (with dependency) still breaks it, It's a rather minor thing, but i thought i would mention it.
 [](url)
![Thunderstore mods](https://user-images.githubusercontent.com/107779658/206514490-bda00691-4d75-45d5-946a-3e478ac31da3.PNG)
![20221208174544_1](https://user-images.githubusercontent.com/107779658/206514494-4b0414f2-7bb3-4069-891c-fada1ec780fb.jpg)
![20221208174620_1](https://user-images.githubusercontent.com/107779658/206514502-9864edb3-9e61-4faa-aa94-8d84d7315173.jpg)

**Comment by HolloFox** [comment]
Was resolved with last update.
